### ISSUE TITLE
color picker uses invalid alpha format

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/intentions-colorpicker#8]
https://v.usetapes.com/Nu25L75YLh

It should be rgba(x,x,x,y)

**Comment by steelbrain** [comment]
It actually supports both of them, if you click the `rgb` tab at the bottom of the dialog and then change the opacity, it'll produce result in that format.

Also this package has no color picker code in itself, it's just a proxy to https://github.com/thomaslindstrom/color-picker

**Comment by ncammarata** [comment]
we should remove any options that will break Flint, or add options in color picker via pull requests that allow us to hide things that break flint

**Comment by steelbrain** [comment]
Filed here https://github.com/thomaslindstrom/color-picker/issues/170
